name: sdk-check

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # Runs at 16:00 UTC on the 1st of every month
  workflow_dispatch:
  #schedule:
  #  - cron:  '*/5 * * * *'

jobs:
  # This workflow contains a single job called "build"
  build:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up Python
          uses: actions/setup-python@v3
          with:
            python-version: 3.8
        - uses: actions/cache@v3
          with:
            path: ~/.local/share
            key: ${{ hashFiles('temp_update_pkgs.json') }}
        - name: Install Python Tools
          shell: bash
          run: |
            sudo apt-get update
            sudo apt-get install python3-pip python3-setuptools python3-wheel -y
            pip install requests wheel jsonschema
        - name: Check SDK Update
          shell: bash
          run: |
            cd ${{ github.workspace }}/tools
            python main.py

